name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
      
    steps:
    - name: Checkout
    - uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      if: ${{ false }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      if: ${{ false }}
